default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: scheduling_app_development
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 5432

test:
  <<: *default
  database: scheduling_app_development

production:
  <<: *default
  database: scheduling_app_development
  # url: <%= ENV['DATABASE_URL'] %>
