default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: scheduling_app_development

test:
  <<: *default
  database: scheduling_app_test

production:
  <<: *default
  # database: scheduling_app_development
  url: <%= ENV['DATABASE_URL'] %>
